const stocks=[
{name:'NTT',ticker:'9432',type:'core',summary:'通信インフラを土台に、少額で積み上げやすい大型株。',business:'携帯・固定通信を中心に、法人向けIT、データセンター、海外事業などで稼ぐ。毎月の通信料金が収益の土台になる。',moat:'全国規模の通信網、巨大な顧客基盤、研究開発力。簡単には真似できないインフラを持つ。',growth:'成熟した通信事業が土台。大幅成長より、法人IT・データセンター・IOWNなどへの投資が次の利益源になるかを見る会社。',metrics:[['売上成長','安定型'],['収益力','高い'],['PER','要最新確認'],['PBR','要最新確認'],['ROE','要最新確認']],point:'成長投資が実際の利益増加につながるか。通信以外の事業が全体を押し上げられるか。',risk:'通信料金競争、規制、巨額投資の回収遅れ。大型株なので短期で何倍にもなるタイプではない。',why:'毎月5,000円の大型株枠と相性がよく、少額で継続しやすい。一方で「安いから買う」ではなく、最新の株価と決算を確認して買う。',judge:'買い候補'},
{name:'三菱商事',ticker:'8058',type:'core',summary:'多様な事業を持つ日本の代表的な総合商社。',business:'資源、食品、電力、素材、モビリティなど幅広い事業への投資と運営で稼ぐ。',moat:'世界中の事業ネットワーク、資金力、案件発掘力。事業分散が効きやすい。',growth:'非資源分野の利益拡大と資産入れ替えが成長の鍵。',metrics:[['売上成長','景気連動'],['収益力','高い'],['PER','要最新確認'],['PBR','要最新確認'],['ROE','要最新確認']],point:'非資源分野の利益成長と株主還元。',risk:'資源価格や世界景気の変動。',why:'優良大型株だが、NTTとの予算配分と買値を見て判断したい。',judge:'待つ'},
{name:'ベイカレント',ticker:'6532',type:'core',summary:'高成長を続ける国内コンサルティング企業。',business:'企業の経営・DX課題にコンサルタントを提供して稼ぐ。',moat:'高い稼働率と採用力、幅広い業界の顧客基盤。',growth:'人員増と単価上昇を利益成長につなげられるかが中心。',metrics:[['売上成長','高成長'],['収益力','高い'],['PER','要最新確認'],['PBR','要最新確認'],['ROE','要最新確認']],point:'売上成長、人材採用、利益率の持続性。',risk:'人材獲得競争と成長鈍化。',why:'持株会で毎月積み立てているため、個別買い増しより保有状況の確認を優先。',judge:'保有継続'},
{name:'PKSHA Technology',ticker:'3993',type:'dream',summary:'AIを企業の実務に実装する成長企業。',business:'AIソフトウェアやアルゴリズムを企業に提供し、継続利用料や導入収益を得る。',moat:'日本企業への実装経験と独自アルゴリズム、顧客接点。',growth:'AI需要を一時的な案件ではなく継続収益へ変えられるか。',metrics:[['売上成長','高成長'],['収益力','成長中'],['PER','要最新確認'],['PBR','要最新確認'],['ROE','要最新確認']],point:'継続収益の伸びと利益率。',risk:'高い期待が株価に織り込まれること。',why:'テーマだけで買わず、成長率と株価評価の両方を追う。',judge:'調査継続'},
{name:'Astroscale',ticker:'186A',type:'dream',summary:'宇宙ごみ除去など軌道上サービスを狙う宇宙企業。',business:'政府・宇宙機関などから軌道上サービスの実証や将来契約を獲得する。',moat:'先行する技術実証と専門人材、各国機関との関係。',growth:'大型契約と商用化が売上拡大の鍵。',metrics:[['売上成長','案件型'],['収益力','赤字'],['PER','対象外'],['PBR','要最新確認'],['ROE','要最新確認']],point:'大型契約、技術実証、商用化の進展。',risk:'赤字継続、開発遅延、資金調達。',why:'成功時の伸びは大きいが不確実性も高い。夢枠の少額候補。',judge:'夢枠候補'},
{name:'Rocket Lab',ticker:'RKLB',type:'dream',summary:'打上げと宇宙システムを手がける米国宇宙企業。',business:'ロケット打上げ、衛星部品、宇宙システムの提供で稼ぐ。',moat:'打上げ実績と宇宙システムを一体で持つ点。',growth:'次世代ロケットNeutronと宇宙システム事業の拡大が焦点。',metrics:[['売上成長','高成長'],['収益力','赤字'],['PER','対象外'],['PBR','要最新確認'],['ROE','要最新確認']],point:'Neutronの開発進捗と受注。',risk:'開発失敗、競争、資金需要。',why:'夢は大きいが、開発マイルストーン確認が先。',judge:'夢枠候補'}];
const list=document.querySelector('#stockList'),count=document.querySelector('#count'),modal=document.querySelector('#detailModal');
function label(t){return t==='core'?'大型株枠':'夢枠'}
function render(filter='all'){const data=filter==='all'?stocks:stocks.filter(s=>s.type===filter);count.textContent=`${data.length}社`;list.innerHTML=data.map(s=>`<button class="stock" data-name="${s.name}"><span class="logo">${s.name.slice(0,1)}</span><span class="meta"><h3>${s.name}</h3><p>${s.ticker} · ${label(s.type)}</p></span><span class="judge">${s.judge}</span></button>`).join('');list.querySelectorAll('.stock').forEach(b=>b.onclick=()=>openDetail(stocks.find(s=>s.name===b.dataset.name)))}
function openDetail(s){['Ticker','Name','Summary','Business','Moat','Growth','Point','Risk','Why','Judge'].forEach(k=>document.querySelector('#detail'+k).textContent=s[k.toLowerCase()]);document.querySelector('#detailBadge').textContent=label(s.type);document.querySelector('#detailMetrics').innerHTML=s.metrics.map(m=>`<div><span>${m[0]}</span><strong>${m[1]}</strong></div>`).join('');modal.showModal();modal.scrollTop=0}
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelector('.tab.active').classList.remove('active');t.classList.add('active');render(t.dataset.filter)});document.querySelector('#closeModal').onclick=()=>modal.close();document.querySelector('#openPick').onclick=()=>openDetail(stocks[0]);modal.onclick=e=>{if(e.target===modal)modal.close()};render();