const stocks=[
{name:'NTT',ticker:'9432',type:'stable',summary:'通信インフラを土台に、少額で積み上げやすい銘柄。',business:'携帯・固定通信を中心に、法人向けIT、データセンター、海外事業などで稼ぐ。',moat:'全国規模の通信網、巨大な顧客基盤、研究開発力。',growth:'法人IT・データセンター・IOWNなどへの投資が次の利益源になるかを見る。',metrics:[['売上成長','安定型'],['収益力','高い'],['PER','要最新確認'],['PBR','要最新確認'],['ROE','要最新確認']],point:'成長投資が実際の利益増加につながるか。',risk:'通信料金競争、規制、巨額投資の回収遅れ。',why:'毎月の予算で少額から継続しやすい。',judge:'買い候補'},
{name:'三菱商事',ticker:'8058',type:'stable',summary:'多様な事業を持つ日本の代表的な総合商社。',business:'資源、食品、電力、素材、モビリティなど幅広い事業への投資と運営で稼ぐ。',moat:'世界中の事業ネットワーク、資金力、案件発掘力。',growth:'非資源分野の利益拡大と資産入れ替えが成長の鍵。',metrics:[['売上成長','景気連動'],['収益力','高い'],['PER','要最新確認'],['PBR','要最新確認'],['ROE','要最新確認']],point:'非資源分野の利益成長と株主還元。',risk:'資源価格や世界景気の変動。',why:'優良銘柄だが、予算配分と買値を見て判断したい。',judge:'待つ'},
{name:'ソニーグループ',ticker:'6758',type:'stable',summary:'ゲーム・音楽・映画・半導体を持つ複合エンタメ企業。',business:'ゲーム、音楽、映画、イメージセンサーなど複数の収益源を持つ。',moat:'世界級のIP、PlayStation、クリエイターとの関係、センサー技術。',growth:'IPをゲーム・映像・音楽へ横展開できるかを見る。',metrics:[['売上成長','安定成長'],['収益力','高い'],['PER','要最新確認'],['PBR','要最新確認'],['ROE','要最新確認']],point:'エンタメの継続成長と半導体投資の回収。',risk:'ヒット依存、為替、半導体投資負担。',why:'日本発の世界企業として長く追いたい。',judge:'注目'},
{name:'キーエンス',ticker:'6861',type:'stable',summary:'高収益で知られる工場自動化の代表企業。',business:'センサーや測定機器を企業へ直接販売して稼ぐ。',moat:'直販営業、高付加価値商品、高い利益率。',growth:'世界の自動化需要を取り込み続けられるか。',metrics:[['売上成長','安定成長'],['収益力','非常に高い'],['PER','要最新確認'],['PBR','要最新確認'],['ROE','要最新確認']],point:'海外成長と高い収益性の持続。',risk:'景気減速、設備投資減少、高い株価評価。',why:'強い会社だが買値の影響が大きい。',judge:'待つ'},
{name:'ベイカレント',ticker:'6532',type:'growth',summary:'高成長を続ける国内コンサルティング企業。',business:'企業の経営・DX課題にコンサルタントを提供して稼ぐ。',moat:'高い稼働率と採用力、幅広い業界の顧客基盤。',growth:'人員増と単価上昇を利益成長につなげられるか。',metrics:[['売上成長','高成長'],['収益力','高い'],['PER','要最新確認'],['PBR','要最新確認'],['ROE','要最新確認']],point:'売上成長、人材採用、利益率の持続性。',risk:'人材獲得競争と成長鈍化。',why:'持株会で毎月積み立てているため保有状況の確認を優先。',judge:'保有継続'},
{name:'リクルートHD',ticker:'6098',type:'growth',summary:'求人マッチングを世界規模で展開する企業。',business:'求人広告、人材紹介、Indeedなどのマッチングで稼ぐ。',moat:'巨大な求人データ、利用者基盤、世界展開。',growth:'AIで求人マッチングの価値を高められるか。',metrics:[['売上成長','成長型'],['収益力','高い'],['PER','要最新確認'],['PBR','要最新確認'],['ROE','要最新確認']],point:'HRテクノロジーの成長再加速。',risk:'景気後退による求人減少、競争。',why:'日本企業の中でも世界で伸びる余地を追いたい。',judge:'注目'},
{name:'PKSHA Technology',ticker:'3993',type:'growth',summary:'AIを企業の実務に実装する成長企業。',business:'AIソフトウェアやアルゴリズムを企業に提供する。',moat:'日本企業への実装経験と独自アルゴリズム、顧客接点。',growth:'AI需要を継続収益へ変えられるか。',metrics:[['売上成長','高成長'],['収益力','成長中'],['PER','要最新確認'],['PBR','要最新確認'],['ROE','要最新確認']],point:'継続収益の伸びと利益率。',risk:'高い期待が株価に織り込まれること。',why:'テーマだけで買わず、成長率と株価評価の両方を追う。',judge:'調査継続'},
{name:'任天堂',ticker:'7974',type:'growth',summary:'世界で愛されるゲームIPを持つ日本企業。',business:'ゲーム機、ソフト、デジタル販売、IP活用で稼ぐ。',moat:'マリオなどの強力なIPと独自のゲーム体験。',growth:'新ハードとIP展開で収益を広げられるか。',metrics:[['売上成長','製品周期型'],['収益力','高い'],['PER','要最新確認'],['PBR','要最新確認'],['ROE','要最新確認']],point:'ハード世代交代後の継続収益。',risk:'ヒット依存、製品サイクル。',why:'IPの長期価値を追いかけたい。',judge:'注目'},
{name:'メルカリ',ticker:'4385',type:'leap',summary:'国内フリマを土台に次の成長を探すテック企業。',business:'売買手数料や決済・金融サービスで稼ぐ。',moat:'国内最大級の利用者基盤と取引データ。',growth:'金融と海外事業が次の柱になるか。',metrics:[['売上成長','成長型'],['収益力','改善中'],['PER','要最新確認'],['PBR','要最新確認'],['ROE','要最新確認']],point:'国内以外の利益源が育つか。',risk:'競争、海外事業、成長鈍化。',why:'再成長できれば評価が変わる余地がある。',judge:'調査継続'},
{name:'Astroscale',ticker:'186A',type:'leap',summary:'宇宙ごみ除去など軌道上サービスを狙う宇宙企業。',business:'政府・宇宙機関などから軌道上サービスの実証や将来契約を獲得する。',moat:'先行する技術実証と専門人材、各国機関との関係。',growth:'大型契約と商用化が売上拡大の鍵。',metrics:[['売上成長','案件型'],['収益力','赤字'],['PER','対象外'],['PBR','要最新確認'],['ROE','要最新確認']],point:'大型契約、技術実証、商用化の進展。',risk:'赤字継続、開発遅延、資金調達。',why:'成功時の伸びは大きいが不確実性も高い。',judge:'飛躍候補'},
{name:'Berkshire Hathaway',ticker:'BRK.B',type:'stable',summary:'多様な事業と投資資産を持つ米国の複合企業。',business:'保険、鉄道、エネルギー、製造と株式投資で稼ぐ。',moat:'巨大な資本、保険の資金、長期投資文化。',growth:'資本を高い効率で再投資できるか。',metrics:[['売上成長','安定型'],['収益力','高い'],['PER','要最新確認'],['PBR','要最新確認'],['ROE','要最新確認']],point:'次世代の資本配分と大型投資。',risk:'巨大化による成長鈍化、後継体制。',why:'長期投資の土台候補として追う。',judge:'注目'},
{name:'Microsoft',ticker:'MSFT',type:'stable',summary:'クラウドとソフトウェアを世界規模で展開する企業。',business:'クラウド、Office、Windows、ゲームなどで継続収益を得る。',moat:'企業顧客との深い関係と巨大なソフトウェア基盤。',growth:'AI投資を実際の売上と利益へ変えられるか。',metrics:[['売上成長','安定成長'],['収益力','非常に高い'],['PER','要最新確認'],['PBR','要最新確認'],['ROE','要最新確認']],point:'AIとクラウドの収益化。',risk:'規制、巨額AI投資、高い株価評価。',why:'世界のIT基盤として長く追いたい。',judge:'注目'},
{name:'Visa',ticker:'V',type:'stable',summary:'世界の決済ネットワークを支える企業。',business:'カード決済額に応じた手数料などで稼ぐ。',moat:'世界規模の加盟店と金融機関ネットワーク。',growth:'現金からデジタル決済への移行が追い風。',metrics:[['売上成長','安定成長'],['収益力','非常に高い'],['PER','要最新確認'],['PBR','要最新確認'],['ROE','要最新確認']],point:'決済額の成長と新しい決済手段への対応。',risk:'規制、新決済技術、景気後退。',why:'長期の構造変化を取り込む候補。',judge:'注目'},
{name:'NVIDIA',ticker:'NVDA',type:'growth',summary:'AI計算基盤の中心にいる半導体企業。',business:'GPU、AI向けシステム、ソフトウェアで稼ぐ。',moat:'高性能GPUとCUDAを中心とした開発者基盤。',growth:'AI投資拡大をどこまで持続的な利益にできるか。',metrics:[['売上成長','高成長'],['収益力','非常に高い'],['PER','要最新確認'],['PBR','要最新確認'],['ROE','要最新確認']],point:'AI需要、競争、次世代製品の供給。',risk:'期待の高さ、競争、顧客集中。',why:'成長力は大きいが買値を慎重に見る。',judge:'調査継続'},
{name:'MercadoLibre',ticker:'MELI',type:'growth',summary:'中南米のECとフィンテックを牽引する企業。',business:'EC手数料、広告、決済、金融サービスで稼ぐ。',moat:'物流・決済を一体化した地域基盤。',growth:'ECと金融の両輪が拡大するか。',metrics:[['売上成長','高成長'],['収益力','成長中'],['PER','要最新確認'],['PBR','要最新確認'],['ROE','要最新確認']],point:'利用者拡大と信用コスト。',risk:'通貨、政治、競争。',why:'地域成長を取り込む世界級企業として追う。',judge:'注目'},
{name:'CrowdStrike',ticker:'CRWD',type:'growth',summary:'クラウド型サイバーセキュリティの成長企業。',business:'企業向けセキュリティソフトの継続課金で稼ぐ。',moat:'脅威データとクラウド基盤、製品追加のしやすさ。',growth:'顧客単価と製品数を伸ばせるか。',metrics:[['売上成長','高成長'],['収益力','改善中'],['PER','要最新確認'],['PBR','要最新確認'],['ROE','要最新確認']],point:'継続率と利益率の改善。',risk:'競争、障害、期待の高さ。',why:'必要性が増す分野の有力企業。',judge:'調査継続'},
{name:'Intuitive Surgical',ticker:'ISRG',type:'growth',summary:'手術支援ロボットの世界的リーダー。',business:'手術ロボット本体と消耗品、サービスで稼ぐ。',moat:'導入台数、医師の習熟、継続的な消耗品収益。',growth:'ロボット手術の対象拡大が続くか。',metrics:[['売上成長','成長型'],['収益力','高い'],['PER','要最新確認'],['PBR','要最新確認'],['ROE','要最新確認']],point:'手術件数と新機種の普及。',risk:'高い株価評価、競争、医療規制。',why:'医療の長期変化を追う候補。',judge:'注目'},
{name:'Palantir',ticker:'PLTR',type:'leap',summary:'企業や政府のデータ活用を支えるAIソフト企業。',business:'データ統合・分析・AIソフトの契約で稼ぐ。',moat:'複雑な現場への導入力と政府分野での実績。',growth:'AI需要を商用顧客の拡大につなげられるか。',metrics:[['売上成長','高成長'],['収益力','改善中'],['PER','要最新確認'],['PBR','要最新確認'],['ROE','要最新確認']],point:'商用顧客と利益成長。',risk:'高い期待、政府依存、競争。',why:'大化け余地と割高リスクを両方追う。',judge:'飛躍候補'},
{name:'Rocket Lab',ticker:'RKLB',type:'leap',summary:'打上げと宇宙システムを手がける米国宇宙企業。',business:'ロケット打上げ、衛星部品、宇宙システムの提供で稼ぐ。',moat:'打上げ実績と宇宙システムを一体で持つ点。',growth:'次世代ロケットNeutronと宇宙システム事業の拡大が焦点。',metrics:[['売上成長','高成長'],['収益力','赤字'],['PER','対象外'],['PBR','要最新確認'],['ROE','要最新確認']],point:'Neutronの開発進捗と受注。',risk:'開発失敗、競争、資金需要。',why:'飛躍余地は大きいが開発マイルストーン確認が先。',judge:'飛躍候補'},
{name:'Coinbase',ticker:'COIN',type:'leap',summary:'暗号資産経済の拡大に賭ける米国プラットフォーム企業。',business:'取引手数料、保管、ステーブルコイン関連などで稼ぐ。',moat:'ブランド、規制対応、個人と機関の顧客基盤。',growth:'取引以外の継続収益を増やせるか。',metrics:[['売上成長','変動大'],['収益力','市況連動'],['PER','要最新確認'],['PBR','要最新確認'],['ROE','要最新確認']],point:'非取引収益と規制環境。',risk:'暗号資産市況、規制、競争。',why:'成功時の伸びは大きいが少額前提で見る。',judge:'飛躍候補'}];
const list=document.querySelector('#stockList'),count=document.querySelector('#count'),modal=document.querySelector('#detailModal');function label(t){return t==='stable'?'安定':t==='growth'?'成長':'飛躍'}function render(filter='all'){const data=filter==='all'?stocks:stocks.filter(s=>s.type===filter);count.textContent=`${data.length}社`;list.innerHTML=data.map(s=>`<button class="stock" data-name="${s.name}"><span class="logo">${s.name.slice(0,1)}</span><span class="meta"><h3>${s.name}</h3><p>${s.ticker} · ${label(s.type)}</p></span><span class="judge">${s.judge}</span></button>`).join('');list.querySelectorAll('.stock').forEach(b=>b.onclick=()=>openDetail(stocks.find(s=>s.name===b.dataset.name)))}function openDetail(s){['Ticker','Name','Summary','Business','Moat','Growth','Point','Risk','Why','Judge'].forEach(k=>document.querySelector('#detail'+k).textContent=s[k.toLowerCase()]);document.querySelector('#detailBadge').textContent=label(s.type);document.querySelector('#detailMetrics').innerHTML=s.metrics.map(m=>`<div><span>${m[0]}</span><strong>${m[1]}</strong></div>`).join('');document.querySelector('#recordJudgement').onclick=()=>{modal.close();const ti=document.querySelector('#decisionTicker');if(ti)ti.value=s.ticker;const sec=document.querySelector('.decision-journal-section');if(sec)sec.scrollIntoView({behavior:'smooth'});const th=document.querySelector('#decisionThesis');if(th)setTimeout(()=>th.focus(),300)};modal.showModal();modal.scrollTop=0}document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelector('.tab.active').classList.remove('active');t.classList.add('active');render(t.dataset.filter)});document.querySelector('#closeModal').onclick=()=>modal.close();modal.onclick=e=>{if(e.target===modal)modal.close()};
const budgetModal=document.querySelector('#budgetModal'),fmt=n=>'¥'+Number(n).toLocaleString('ja-JP'),values=[...Array.from({length:51},(_,i)=>i*1000),...Array.from({length:95},(_,i)=>(i+6)*10000)];let budget=Number(localStorage.getItem('dfl-monthly-budget'))||5000,draft=budget;const wheel=document.querySelector('#budgetWheel'),budgetInput=document.querySelector('#budgetInput');wheel.innerHTML='<div class="wheel-pad"></div>'+values.map(v=>`<div class="wheel-item">${fmt(v)}</div>`).join('')+'<div class="wheel-pad"></div>';let timer;wheel.onscroll=()=>{clearTimeout(timer);timer=setTimeout(()=>{const idx=Math.min(values.length-1,Math.max(0,Math.round(wheel.scrollTop/48)));draft=values[idx];budgetInput.value='';document.querySelector('#editTotal').textContent=fmt(draft)},80)};budgetInput.oninput=()=>{const raw=budgetInput.value.replace(/[^0-9]/g,'');budgetInput.value=raw;if(raw){draft=Number(raw);document.querySelector('#editTotal').textContent=fmt(draft)}};function showBudget(){document.querySelector('#budgetTotal').textContent=fmt(budget)}document.querySelector('#openBudget').onclick=()=>{draft=budget;budgetInput.value='';budgetModal.showModal();requestAnimationFrame(()=>{let idx=values.indexOf(draft);if(idx<0){budgetInput.value=String(draft);idx=values.reduce((best,v,i)=>Math.abs(v-draft)<Math.abs(values[best]-draft)?i:best,0)}wheel.scrollTop=idx*48;document.querySelector('#editTotal').textContent=fmt(draft)})};document.querySelector('#closeBudget').onclick=()=>budgetModal.close();document.querySelector('#saveBudget').onclick=()=>{budget=Math.max(0,Math.round(draft));localStorage.setItem('dfl-monthly-budget',budget);showBudget();budgetModal.close()};const consultInput=document.querySelector('#consultInput');document.querySelector('#sendConsult').onclick=()=>{if(!consultInput.value.trim()){consultInput.focus();return}localStorage.setItem('dfl-last-consult',consultInput.value.trim());alert('相談内容を受け取りました。次にAIの回答機能をつなげます。')};showBudget();render();