const STORAGE_KEY='dream_fund_purchase_alerts';
const MONTHLY_BUDGET_KEY='dfl-monthly-budget';
const DEFAULT_MONTHLY_BUDGET=5000;
const BUFFER_RATE=1.05;
const FEE_RATE=1.00495;
const STALE_AFTER_MS=36*60*60*1000;
const yen=new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0});
const usd=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:2});
const dateTime=new Intl.DateTimeFormat('ja-JP',{dateStyle:'short',timeStyle:'short'});
function monthlyBudget(){const value=Number(localStorage.getItem(MONTHLY_BUDGET_KEY));return Number.isFinite(value)&&value>0?value:DEFAULT_MONTHLY_BUDGET;}
function mount(){if(document.getElementById('decisionWatch'))return;const css=document.createElement('link');css.rel='stylesheet';css.href='/decision-watch.css?v=3';document.head.appendChild(css);const section=document.createElement('section');section.id='decisionWatch';section.className='decision-watch';section.dataset.status='STALE';section.innerHTML='<div class="decision-watch-head"><div><p class="eyebrow">DECISION WATCH</p><h2 id="watchStatus">OKLOの購入可否を確認中</h2></div><span class="watch-status-dot"></span></div><p class="decision-watch-reason">今月の上限と推定必要額を比較して判定します。</p><div class="watch-primary"><div><span>推定必要額</span><strong id="watchRequired">取得中</strong></div><div><span>判定</span><strong id="watchDecision">確認中</strong></div></div><div class="watch-market"><div><span>OKLO 前日終値</span><strong id="watchPrice">—</strong></div><div><span>USD/JPY</span><strong id="watchFx">—</strong></div></div><dl class="watch-meta"><div><dt>今月の上限</dt><dd id="watchBudget">—</dd></div><div><dt>最終更新</dt><dd id="watchUpdated">未取得</dd></div></dl><p id="watchError" class="watch-error" hidden></p><div class="watch-actions"><button id="refreshWatch" type="button">最新情報に更新</button><button id="markPurchased" class="secondary" type="button">OKLOを購入済みにする</button></div><p class="watch-note">前日終値と参考為替による概算です。実際の注文可否はSBI証券で最終確認してください。</p>';document.querySelector('.consult-card')?.insertAdjacentElement('afterend',section);}
function saveAlert(alert){localStorage.setItem(STORAGE_KEY,JSON.stringify([alert]));}
function readAlert(){try{const list=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');if(Array.isArray(list)&&list[0])return list[0];}catch{}const alert={ticker:'OKLO',stockPriceUsd:null,usdJpy:null,estimatedRequiredJpy:null,status:'STALE',updatedAt:null,notifiedAt:null,purchasedAt:null};saveAlert(alert);return alert;}
function deriveStatus(alert){if(alert.purchasedAt)return'PURCHASED';if(!alert.updatedAt||!Number.isFinite(alert.estimatedRequiredJpy))return'STALE';if(Date.now()-new Date(alert.updatedAt).getTime()>STALE_AFTER_MS)return'STALE';return alert.estimatedRequiredJpy<=monthlyBudget()?'READY':'WAITING';}
function render(alert,errorMessage=''){const card=document.getElementById('decisionWatch');if(!card)return;if(alert.purchasedAt){card.remove();return;}alert.status=deriveStatus(alert);card.dataset.status=alert.status;const label=alert.status==='READY'?'OKLOは購入可能':alert.status==='WAITING'?'OKLOは購入不可':'OKLOの購入可否を確認中';document.getElementById('watchStatus').textContent=label;document.getElementById('watchDecision').textContent=alert.status==='READY'?'購入可能':alert.status==='WAITING'?'購入不可':'確認中';document.getElementById('watchRequired').textContent=Number.isFinite(alert.estimatedRequiredJpy)?yen.format(alert.estimatedRequiredJpy):'取得中';document.getElementById('watchBudget').textContent=yen.format(monthlyBudget());document.getElementById('watchPrice').textContent=Number.isFinite(alert.stockPriceUsd)?usd.format(alert.stockPriceUsd):'—';document.getElementById('watchFx').textContent=Number.isFinite(alert.usdJpy)?`${alert.usdJpy.toFixed(2)}円`:'—';document.getElementById('watchUpdated').textContent=alert.updatedAt?dateTime.format(new Date(alert.updatedAt)):'未取得';const error=document.getElementById('watchError');error.hidden=!errorMessage;error.textContent=errorMessage;saveAlert(alert);}
async function refresh(){const button=document.getElementById('refreshWatch');if(!button)return;button.disabled=true;button.textContent='更新中…';const alert=readAlert();try{const response=await fetch('/api/market/quote?symbol=OKLO',{cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data?.error||'市場データを取得できませんでした');alert.stockPriceUsd=Number(data.stockPriceUsd);alert.usdJpy=Number(data.usdJpy);alert.estimatedRequiredJpy=Math.ceil(alert.stockPriceUsd*alert.usdJpy*BUFFER_RATE*FEE_RATE);alert.updatedAt=data.fetchedAt||new Date().toISOString();render(alert);}catch(error){render(alert,error.message);}finally{button.disabled=false;button.textContent='最新情報に更新';}}
function init(){mount();const alert=readAlert();if(alert.purchasedAt)return render(alert);render(alert);document.getElementById('refreshWatch')?.addEventListener('click',refresh);document.getElementById('markPurchased')?.addEventListener('click',()=>{if(!confirm('OKLOを購入済みにして表示を消しますか？'))return;const current=readAlert();current.purchasedAt=new Date().toISOString();saveAlert(current);document.getElementById('decisionWatch')?.remove();});refresh();}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();